BLOOCK_DB_CONNECTION_STRING: "file:bloock?mode=memory&cache=shared&_fk=1"
BLOOCK_API_KEY: "tFD-hh1QYTj1TQEp3LulhHAredSkekobuuZI8vduysc7sx2RZTdpnX6A5FSQuSvT"
BLOOCK_CLIENT_ENDPOINT_URL: "https://4a1c-94-132-61-84.ngrok-free.app/v1/certification"
BLOOCK_WEBHOOK_SECRET_KEY:  0yh32cDYNW3F68WuELH36qXWgk5I8L1n
BLOOCK_AUTHENTICITY_PRIVATE_KEY: ""
BLOOCK_AUTHENTICITY_PUBLIC_KEY: ""
BLOOCK_API_HOST: "0.0.0.0"
BLOOCK_API_PORT: "8080"
BLOOCK_ENFORCE_TOLERANCE: false
BLOOCK_API_DEBUG_MODE: "true"