BLOOCK_API_HOST: "0.0.0.0"
BLOOCK_API_PORT: "8080"
BLOOCK_API_DEBUG_MODE: false

BLOOCK_DB_CONNECTION_STRING: "file:bloock?mode=memory&cache=shared&_fk=1"

BLOOCK_API_KEY: ""
BLOOCK_WEBHOOK_SECRET_KEY: ""

BLOOCK_CLIENT_ENDPOINT_URL: ""

BLOOCK_AUTHENTICITY_PRIVATE_KEY: ""
BLOOCK_AUTHENTICITY_PUBLIC_KEY: ""

BLOOCK_ENCRYPTION_PRIVATE_KEY: ""
BLOOCK_ENCRYPTION_PUBLIC_KEY: ""

BLOOCK_TMP_DIR: "./tmp"
BLOOCK_STORAGE_LOCAL_PATH: "./data"
