BLOOCK_DB_CONNECTION_STRING: "file:bloock?mode=memory&cache=shared&_fk=1"
BLOOCK_API_KEY: ""
BLOOCK_WEBHOOK_URL:
BLOOCK_WEBHOOK_SECRET_KEY:  ""
BLOOCK_API_HOST: "0.0.0.0"
BLOOCK_API_PORT: "8080"
BLOOCK_ENFORCE_TOLERANCE: true
BLOOCK_API_DEBUG_MODE: false