DBConnectionString: "file:bloock?mode=memory&cache=shared&_fk=1"
APIKey: "Nm1sFmrojcrRgfZ4v0H0w0d1d22GookjcJl7y-2jr51qx0RioCR3nVm1z74hDEzZ"
WebhookURL: "https://google.com"
WebhookSecretKey:  ""
APIHost: "0.0.0.0"
APIPort: "8080"
WebhookEnforceTolerance: true
ApiDebugMode: false