api:
  host: "0.0.0.0"
  port: 8080
  debug_mode: true

db:
  connection_string: "postgresql://postgres:admin@localhost:5432/managed?sslmode=disable"

auth:
  secret: ""

bloock:
  api_host: "https://api.bloock.dev"
  api_key: "Fw93zvHaTu7VZeb50mfQi1C-K1iMWRJ0obFHUbvypInmz78hG-y0ZLSZKBo0H0V4"
  cdn_host: "https://cdn.bloock.dev"
  webhook_secret_key: ""

webhook:
  client_endpoint_url: ""
  max_retries:

authenticity:
  key:
    key_type: ""
    key: ""
  certificate:
    pkcs12_path: "./"
    pkcs12_password: ""

encryption:
  key:
    key_type: ""
    key: ""
  certificate:
    pkcs12_path: "./"
    pkcs12_password: ""

integrity:
  aggregate_mode: false
  aggregate_worker: false
  aggregate_interval:

storage:
  tmp_dir: "./tmp"
  local_strategy: "FILENAME"
  local_path: "./data"