BLOOCK_DB_CONNECTION_STRING: "file:bloock?mode=memory&cache=shared&_fk=1"
BLOOCK_API_KEY: "jMPDphTBAQNgVmTOaCSnGDvVYnVadGRrSd6z-3JmgunBv0yDhdn0uJT-FUSWgFgD"
BLOOCK_CLIENT_ENDPOINT_URL: ""
BLOOCK_WEBHOOK_SECRET_KEY: 0yh32cDYNW3F68WuELH36qXWgk5I8L1n
BLOOCK_AUTHENTICITY_PRIVATE_KEY: ""
BLOOCK_AUTHENTICITY_PUBLIC_KEY: ""
BLOOCK_ENCRYPTION_PRIVATE_KEY: ""
BLOOCK_ENCRYPTION_PUBLIC_KEY: "password"
BLOOCK_API_HOST: "0.0.0.0"
BLOOCK_API_PORT: "8080"
BLOOCK_FILE_DIR: "./tmp"
BLOOCK_API_DEBUG_MODE: "true"
