api:
  host: "0.0.0.0"
  port: 8080
  debug_mode: false

db:
  connection_string: "file:bloock?mode=memory&cache=shared&_fk=1"

bloock:
  api_host: "https://api.bloock.dev"
  api_key: "ygTYw85v26j1Zazm61CpJdhMaOB53kZTJvDTaS0Qlw9-LPJS1LSbQAS91ZvZiq45"
  cdn_host: "https://cdn.bloock.dev"
  webhook_secret_key: ""

webhook:
  client_endpoint_url: ""

authenticity:
  key:
    key_type: ""
    key: ""
  certificate:
    pkcs12_path: "./"
    pkcs12_password: ""

encryption:
  key:
    key_type: ""
    key: ""
  certificate:
    pkcs12_path: "./"
    pkcs12_password: ""

storage:
  tmp_dir: "./tmp"
  local_strategy: "FILENAME"
  local_path: "./data"
