services:
  bloock-managed-api:
    image: bloock/managed-api:latest
    container_name: bloock-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
      - ./data:/go/bin/data
    ports:
      - 8080:8080
    environment:
      BLOOCK_API_KEY: ""
