services:
  bloock-managed-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloock-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
    environment:
      BLOOCK_DB_CONNECTION_STRING: "file:managed?mode=memory&cache=shared&_fk=1"
      BLOOCK_API_KEY: ""
      BLOOCK_CLIENT_ENDPOINT_URL: ""
      BLOOCK_WEBHOOK_SECRET_KEY:
      BLOOCK_API_HOST: "0.0.0.0"
      BLOOCK_API_PORT: "8080"
      BLOOCK_API_DEBUG_MODE:
      BLOOCK_AUTHENTICITY_PRIVATE_KEY: ""
      BLOOCK_AUTHENTICITY_PUBLIC_KEY: ""
      BLOOCK_MAX_MEMORY:
      BLOOCK_FILE_DIR:
