services:
  postgres:
    platform: linux/x86_64
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  bloock-managed-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloock-managed-api
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      BLOOCK_DB_CONNECTION_STRING: "postgres://admin:admin@tcp(postgres:3306)/managed"
      BLOOCK_API_KEY: "Nm1sFmrojcrRgfZ4v0H0w0d1d22GookjcJl7y-2jr51qx0RioCR3nVm1z74hDEzZ"
      BLOOCK_WEBHOOK_URL: "https://bloock-managedapi.ultrahook.com"
      BLOOCK_WEBHOOK_SECRET_KEY: "1AI1yw3JsqPODg0KLRLcyn62BfxUbXcn"
      BLOOCK_API_HOST: "0.0.0.0"
      BLOOCK_API_PORT: "8080"
      BLOOCK_ENFORCE_TOLERANCE: false
