services:
  bloock-managed-api:
    image: bloock/managed-api:latest
    container_name: bloock-managed-api
    volumes:
      - ./config.yaml:/home/nonroot/app/config.yaml:ro
      - ./data:/home/nonroot/app/data
    ports:
      - 8080:8080
    environment:
      BLOOCK_BLOOCK_API_KEY: ""
      BLOOCK_BLOOCK_WEBHOOK_SECRET_KEY: ""
      BLOOCK_WEBHOOK_CLIENT_ENDPOINT_URL: ""