services:
  bloock-managed-api:
    image: bloock/managed-api:latest
    container_name: bloock-managed-api
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    ports:
      - 8080:8080
    environment:
      BLOOCK_API_KEY: ""
