services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: managed
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  bloock-managed-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloock-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      BLOOCK_DB_CONNECTION_STRING: "mysql://root:admin@tcp(mysql:3306)/managed"
