services:
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: managed
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  bloock-managed-api:
    image: bloock/managed-api:latest
    container_name: bloock-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      BLOOCK_DB_CONNECTION_STRING: "mysql://root:admin@tcp(mysql:3306)/managed"
      BLOOCK_API_KEY: ""
      BLOOCK_CLIENT_ENDPOINT_URL: ""
      BLOOCK_WEBHOOK_SECRET_KEY: ""
      BLOOCK_AUTHENTICITY_PRIVATE_KEY: ""
      BLOOCK_AUTHENTICITY_PUBLIC_KEY: ""
      BLOOCK_API_HOST: "0.0.0.0"
      BLOOCK_API_PORT: "8080"
      BLOOCK_API_DEBUG_MODE: false
      BLOOCK_FILE_DIR: ""
