services:
  postgres:
    platform: linux/x86_64
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  bloock-managed-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloock-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      BLOOCK_DB_CONNECTION_STRING: "postgres://admin:admin@tcp(postgres:3306)/managed"
      BLOOCK_API_KEY: ""
      BLOOCK_CLIENT_ENDPOINT_URL: ""
      BLOOCK_WEBHOOK_SECRET_KEY: ""
      BLOOCK_API_HOST: "0.0.0.0"
      BLOOCK_API_PORT: "8080"
      BLOOCK_ENFORCE_TOLERANCE: false
      BLOOCK_API_DEBUG_MODE:
      BLOOCK_AUTHENTICITY_PRIVATE_KEY: ""
      BLOOCK_AUTHENTICITY_PUBLIC_KEY: ""
      BLOOCK_MAX_MEMORY:

