services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: managed
    ports:
      - "3306:3306"

  bloock-managed-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloock-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      BLOOCK_DB_CONNECTION_STRING: "mysql://admin:admin@tcp(mysql:3306)/managed"
      BLOOCK_API_KEY: ""
      BLOOCK_CLIENT_ENDPOINT_URL: ""
      BLOOCK_WEBHOOK_SECRET_KEY: ""
      BLOOCK_API_HOST: "0.0.0.0"
      BLOOCK_API_PORT: "8080"
      BLOOCK_ENFORCE_TOLERANCE: false
      BLOOCK_API_DEBUG_MODE:
      BLOOCK_AUTHENTICITY_PRIVATE_KEY: ""
      BLOOCK_AUTHENTICITY_PUBLIC_KEY: ""
      BLOOCK_MAX_MEMORY:

