services:
  bloock-managed-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloock-managed-api
    volumes:
      - ./config.yml:/go/bin/config.yml:ro
    ports:
      - 8080:8080
