// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CertificationsColumns holds the columns for the "certifications" table.
	CertificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "anchor_id", Type: field.TypeInt},
		{Name: "anchor", Type: field.TypeJSON},
		{Name: "hash", Type: field.TypeString},
	}
	// CertificationsTable holds the schema information for the "certifications" table.
	CertificationsTable = &schema.Table{
		Name:       "certifications",
		Columns:    CertificationsColumns,
		PrimaryKey: []*schema.Column{CertificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "certification_id_hash_anchor",
				Unique:  true,
				Columns: []*schema.Column{CertificationsColumns[0], CertificationsColumns[3], CertificationsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CertificationsTable,
	}
)

func init() {
}
