// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Certification is the predicate function for certification builders.
type Certification func(*sql.Selector)
