// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Certification is the predicate function for certification builders.
type Certification func(*sql.Selector)

// LocalKey is the predicate function for localkey builders.
type LocalKey func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Process is the predicate function for process builders.
type Process func(*sql.Selector)
