// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bloock/bloock-managed-api/internal/platform/repository/sql/ent/message"
	"github.com/bloock/bloock-managed-api/internal/platform/repository/sql/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetMessage sets the "message" field.
func (mu *MessageUpdate) SetMessage(s string) *MessageUpdate {
	mu.mutation.SetMessage(s)
	return mu
}

// SetRoot sets the "root" field.
func (mu *MessageUpdate) SetRoot(s string) *MessageUpdate {
	mu.mutation.SetRoot(s)
	return mu
}

// SetNillableRoot sets the "root" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableRoot(s *string) *MessageUpdate {
	if s != nil {
		mu.SetRoot(*s)
	}
	return mu
}

// SetAnchorID sets the "anchor_id" field.
func (mu *MessageUpdate) SetAnchorID(i int) *MessageUpdate {
	mu.mutation.ResetAnchorID()
	mu.mutation.SetAnchorID(i)
	return mu
}

// SetNillableAnchorID sets the "anchor_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableAnchorID(i *int) *MessageUpdate {
	if i != nil {
		mu.SetAnchorID(*i)
	}
	return mu
}

// AddAnchorID adds i to the "anchor_id" field.
func (mu *MessageUpdate) AddAnchorID(i int) *MessageUpdate {
	mu.mutation.AddAnchorID(i)
	return mu
}

// SetProof sets the "proof" field.
func (mu *MessageUpdate) SetProof(jm json.RawMessage) *MessageUpdate {
	mu.mutation.SetProof(jm)
	return mu
}

// AppendProof appends jm to the "proof" field.
func (mu *MessageUpdate) AppendProof(jm json.RawMessage) *MessageUpdate {
	mu.mutation.AppendProof(jm)
	return mu
}

// ClearProof clears the value of the "proof" field.
func (mu *MessageUpdate) ClearProof() *MessageUpdate {
	mu.mutation.ClearProof()
	return mu
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.Message(); ok {
		if err := message.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Message.message": %w`, err)}
		}
	}
	if v, ok := mu.mutation.AnchorID(); ok {
		if err := message.AnchorIDValidator(v); err != nil {
			return &ValidationError{Name: "anchor_id", err: fmt.Errorf(`ent: validator failed for field "Message.anchor_id": %w`, err)}
		}
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Message(); ok {
		_spec.SetField(message.FieldMessage, field.TypeString, value)
	}
	if value, ok := mu.mutation.Root(); ok {
		_spec.SetField(message.FieldRoot, field.TypeString, value)
	}
	if value, ok := mu.mutation.AnchorID(); ok {
		_spec.SetField(message.FieldAnchorID, field.TypeInt, value)
	}
	if value, ok := mu.mutation.AddedAnchorID(); ok {
		_spec.AddField(message.FieldAnchorID, field.TypeInt, value)
	}
	if value, ok := mu.mutation.Proof(); ok {
		_spec.SetField(message.FieldProof, field.TypeJSON, value)
	}
	if value, ok := mu.mutation.AppendedProof(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldProof, value)
		})
	}
	if mu.mutation.ProofCleared() {
		_spec.ClearField(message.FieldProof, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetMessage sets the "message" field.
func (muo *MessageUpdateOne) SetMessage(s string) *MessageUpdateOne {
	muo.mutation.SetMessage(s)
	return muo
}

// SetRoot sets the "root" field.
func (muo *MessageUpdateOne) SetRoot(s string) *MessageUpdateOne {
	muo.mutation.SetRoot(s)
	return muo
}

// SetNillableRoot sets the "root" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableRoot(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetRoot(*s)
	}
	return muo
}

// SetAnchorID sets the "anchor_id" field.
func (muo *MessageUpdateOne) SetAnchorID(i int) *MessageUpdateOne {
	muo.mutation.ResetAnchorID()
	muo.mutation.SetAnchorID(i)
	return muo
}

// SetNillableAnchorID sets the "anchor_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableAnchorID(i *int) *MessageUpdateOne {
	if i != nil {
		muo.SetAnchorID(*i)
	}
	return muo
}

// AddAnchorID adds i to the "anchor_id" field.
func (muo *MessageUpdateOne) AddAnchorID(i int) *MessageUpdateOne {
	muo.mutation.AddAnchorID(i)
	return muo
}

// SetProof sets the "proof" field.
func (muo *MessageUpdateOne) SetProof(jm json.RawMessage) *MessageUpdateOne {
	muo.mutation.SetProof(jm)
	return muo
}

// AppendProof appends jm to the "proof" field.
func (muo *MessageUpdateOne) AppendProof(jm json.RawMessage) *MessageUpdateOne {
	muo.mutation.AppendProof(jm)
	return muo
}

// ClearProof clears the value of the "proof" field.
func (muo *MessageUpdateOne) ClearProof() *MessageUpdateOne {
	muo.mutation.ClearProof()
	return muo
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.Message(); ok {
		if err := message.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Message.message": %w`, err)}
		}
	}
	if v, ok := muo.mutation.AnchorID(); ok {
		if err := message.AnchorIDValidator(v); err != nil {
			return &ValidationError{Name: "anchor_id", err: fmt.Errorf(`ent: validator failed for field "Message.anchor_id": %w`, err)}
		}
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Message(); ok {
		_spec.SetField(message.FieldMessage, field.TypeString, value)
	}
	if value, ok := muo.mutation.Root(); ok {
		_spec.SetField(message.FieldRoot, field.TypeString, value)
	}
	if value, ok := muo.mutation.AnchorID(); ok {
		_spec.SetField(message.FieldAnchorID, field.TypeInt, value)
	}
	if value, ok := muo.mutation.AddedAnchorID(); ok {
		_spec.AddField(message.FieldAnchorID, field.TypeInt, value)
	}
	if value, ok := muo.mutation.Proof(); ok {
		_spec.SetField(message.FieldProof, field.TypeJSON, value)
	}
	if value, ok := muo.mutation.AppendedProof(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldProof, value)
		})
	}
	if muo.mutation.ProofCleared() {
		_spec.ClearField(message.FieldProof, field.TypeJSON)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
