name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:

  test:
    runs-on: ubuntu-latest
    name: Test

    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          go install github.com/golang/mock/mockgen@v1.6.0
          go install entgo.io/ent/cmd/ent@latest
          make cache
          make mocks
      - name: Run tests
        run: make test

  name: ci

  on:
    push:
      branches:
        - 'main'

  docker:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: neifibloock
          password: bloodDev1234
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: neifibloock/managed-api:latest