name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Test
    needs: [ build ]

    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Setup
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
          make mocks
          make schema
      - name: Run tests
        run: make test
