name: build_and_push

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  qa:
    name: "QA Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
        fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - run: "make cache"
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
        version: "2022.1.1"
        install-go: false


  test:
    runs-on: ubuntu-latest
    name: Test
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
          go install entgo.io/ent/cmd/ent@latest
          make cache
          make mocks
      - name: Run tests
        run: make test
