name: CI

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
  test:
    runs-on: ubuntu-latest
    name: Test
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.0
    - name: Setup
      run: |
        go install github.com/golang/mock/mockgen@v1.6.0
        go install entgo.io/ent/cmd/ent@v0.13.1
        make cache
        make mocks
    - name: Run tests
      run: make test
      env:
        API_HOST: ${{ secrets.API_HOST }}
        API_KEY: ${{ secrets.API_KEY }}
        SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
