name: build_and_push

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  qa:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          build-tags:


  test:
    runs-on: ubuntu-latest
    name: Test

    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
          go install entgo.io/ent/cmd/ent@latest
          make cache
          make mocks
      - name: Run tests
        run: make test

